/** Maps country slug to ISO 3166-1 alpha-2 code for use with flag-icons */
export const SLUG_TO_ISO: Record<string, string> = {
  'france': 'fr',
  'germany': 'de',
  'united-states': 'us',
  'united-kingdom': 'gb',
  'canada': 'ca',
  'australia': 'au',
  'portugal': 'pt',
  'spain': 'es',
  'italy': 'it',
  'netherlands': 'nl',
  'sweden': 'se',
  'norway': 'no',
  'denmark': 'dk',
  'finland': 'fi',
  'switzerland': 'ch',
  'austria': 'at',
  'ireland': 'ie',
  'poland': 'pl',
  'belgium': 'be',
  'singapore': 'sg',
  'japan': 'jp',
  'south-korea': 'kr',
  'thailand': 'th',
  'vietnam': 'vn',
  'malaysia': 'my',
  'indonesia': 'id',
  'philippines': 'ph',
  'india': 'in',
  'china': 'cn',
  'uae': 'ae',
  'saudi-arabia': 'sa',
  'brazil': 'br',
  'mexico': 'mx',
  'argentina': 'ar',
  'colombia': 'co',
  'chile': 'cl',
  'new-zealand': 'nz',
  'south-africa': 'za',
  'nigeria': 'ng',
  'kenya': 'ke',
  'ghana': 'gh',
  'egypt': 'eg',
  'morocco': 'ma',
  'georgia': 'ge',
  'ukraine': 'ua',
  'czech-republic': 'cz',
  'hungary': 'hu',
  'romania': 'ro',
  'croatia': 'hr',
  'estonia': 'ee',
  'serbia': 'rs',
  'cyprus': 'cy',
  'latvia': 'lv',
  'lithuania': 'lt',
  'slovakia': 'sk',
  'slovenia': 'si',
  'bulgaria': 'bg',
  'greece': 'gr',
  'turkey': 'tr',
  'israel': 'il',
  'panama': 'pa',
  'costa-rica': 'cr',
  'taiwan': 'tw',
  'pakistan': 'pk',
}

/** Get ISO alpha-2 code from a country slug, or undefined if not mapped */
export function slugToIso(slug: string): string | undefined {
  return SLUG_TO_ISO[slug]
}
