// lib/mappers.ts
import { CountryWithData } from '@/types'

export function mapRowToCountry(c: any, d: any): CountryWithData {
  return {
    id: c.id,
    slug: c.slug,
    name: c.name,
    flagEmoji: c.flag_emoji,
    continent: c.continent,
    lat: c.lat,
    lng: c.lng,
    currency: c.currency,
    language: c.language,
    data: {
      id: d.id,
      countryId: d.country_id,
      salarySoftwareEngineer: d.salary_software_engineer,
      salaryNurse: d.salary_nurse,
      salaryTeacher: d.salary_teacher,
      salaryAccountant: d.salary_accountant,
      salaryMarketingManager: d.salary_marketing_manager,
      salaryDoctor: d.salary_doctor,
salaryDataScientist: d.salary_data_scientist,
salaryProductManager: d.salary_product_manager,
salaryUXDesigner: d.salary_ux_designer,
salaryDevOps: d.salary_devops,
salaryCivilEngineer: d.salary_civil_engineer,
salaryFinancialAnalyst: d.salary_financial_analyst,
salaryLawyer: d.salary_lawyer,
salaryPharmacist: d.salary_pharmacist,
salaryArchitect: d.salary_architect,
salaryHRManager: d.salary_hr_manager,
salarySalesManager: d.salary_sales_manager,
salaryCybersecurity: d.salary_cybersecurity,
salaryElectrician: d.salary_electrician,
salaryChef: d.salary_chef,
      costRentCityCentre: d.cost_rent_city_centre,
      costRentOutside: d.cost_rent_outside,
      costGroceriesMonthly: d.cost_groceries_monthly,
      costTransportMonthly: d.cost_transport_monthly,
      costUtilitiesMonthly: d.cost_utilities_monthly,
      costEatingOut: d.cost_eating_out,
      scoreQualityOfLife: d.score_quality_of_life,
      scoreHealthcare: d.score_healthcare,
      scoreSafety: d.score_safety,
      scoreCrimeRate: d.score_crime_rate ?? 0,
      scoreInternetSpeed: d.score_internet_speed,
      incomeTaxRateMid: d.income_tax_rate_mid,
      socialSecurityRate: d.social_security_rate,
      visaDifficulty: d.visa_difficulty,
      visaNotes: d.visa_notes,
      visaPopularRoutes: d.visa_popular_routes,
      visaOfficialUrl: d.visa_official_url,
      moveScore: d.move_score,
      lastVerified: d.last_verified,
    },
  }
}

import { City, CityData, Neighbourhood } from '@/types'

export function mapRowToCity(row: any): City {
  const d = row.city_data?.[0] ?? {};
  return {
    id: row.id,
    slug: row.slug,
    name: row.name,
    countrySlug: row.country_slug,
    countryName: row.country_name,
    flagEmoji: row.flag_emoji,
    continent: row.continent,
    language: row.language,
    currency: row.currency,
    timezone: row.timezone,
    population: row.population ?? '',
    coverImageUrl: row.cover_image_url ?? null,
    tagline: row.tagline ?? '',
    data: {
      costRentCityCentre:     d.cost_rent_city_centre,
      costRentOutside:        d.cost_rent_outside,
      costGroceriesMonthly:   d.cost_groceries_monthly,
      costTransportMonthly:   d.cost_transport_monthly,
      costEatingOut:          d.cost_eating_out,
      costUtilitiesMonthly:   d.cost_utilities_monthly,
      costGymMonthly:         d.cost_gym_monthly,
      costCoworkingMonthly:   d.cost_coworking_monthly,
      salarySoftwareEngineer: d.salary_software_engineer,
      salaryDoctor:           d.salary_doctor,
      salaryNurse:            d.salary_nurse,
      salaryDataScientist:    d.salary_data_scientist,
      salaryProductManager:   d.salary_product_manager,
      salaryDevOps:           d.salary_devops,
      salaryCybersecurity:    d.salary_cybersecurity,
      salaryUXDesigner:       d.salary_ux_designer,
      salaryFinancialAnalyst: d.salary_financial_analyst,
      salaryLawyer:           d.salary_lawyer,
      salaryArchitect:        d.salary_architect,
      salaryCivilEngineer:    d.salary_civil_engineer,
      salaryPharmacist:       d.salary_pharmacist,
      salaryTeacher:          d.salary_teacher,
      salaryAccountant:       d.salary_accountant,
      salaryHRManager:        d.salary_hr_manager,
      salarySalesManager:     d.salary_sales_manager,
      salaryMarketingManager: d.salary_marketing_manager,
      salaryElectrician:      d.salary_electrician,
      salaryChef:             d.salary_chef,
      scoreQualityOfLife:     d.score_quality_of_life,
      scoreSafety:            d.score_safety,
      scoreHealthcare:        d.score_healthcare,
      scoreInternetSpeed:     d.score_internet_speed,
      scoreWalkability:       d.score_walkability,
      scoreNightlife:         d.score_nightlife,
      scoreExpatFriendliness: d.score_expat_friendliness,
      climateSummerAvgC:      d.climate_summer_avg_c,
      climateWinterAvgC:      d.climate_winter_avg_c,
      climateRainyDaysPerYear:d.climate_rainy_days_per_year,
      climateDescription:     d.climate_description,
      neighbourhoods:         (d.neighbourhoods ?? []) as Neighbourhood[],
      visaNotes:              d.visa_notes,
      visaOfficialUrl:        d.visa_official_url,
      incomeTaxRateMid:       d.income_tax_rate_mid,
      localTaxNote:           d.local_tax_note ?? null,
      moveScore:              d.move_score,
      lastVerified:           d.last_verified,
      dataSources:            d.data_sources,
    },
  };
}